# Generated by Django 3.0.7 on 2020-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainBanner', models.ImageField(upload_to='banner')),
                ('subBanner1', models.ImageField(upload_to='banner')),
                ('subBanner2', models.ImageField(upload_to='banner')),
            ],
        ),
    ]
