# Generated by Django 3.0.7 on 2020-06-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productImg', models.ImageField(upload_to='productsImg')),
                ('productCategories', models.CharField(max_length=200)),
                ('productcolour', models.CharField(max_length=200)),
                ('productPrice', models.IntegerField()),
                ('productOffer', models.BooleanField(default=False)),
                ('OfferPercent', models.IntegerField()),
            ],
        ),
    ]
