# Generated by Django 3.0.7 on 2020-06-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_product_posted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='posted_on',
        ),
    ]
