# Generated by Django 3.0.7 on 2020-06-19 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_remove_product_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
