# Generated by Django 3.0.7 on 2020-06-20 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0007_siteinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='supportTime',
            new_name='supportDay',
        ),
    ]
