# Generated by Django 3.0.7 on 2020-06-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0009_siteinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featuredproduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
