# Generated by Django 3.0.7 on 2020-06-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0011_auto_20200620_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImg2',
            field=models.ImageField(blank=True, upload_to='productsImg'),
        ),
        migrations.AddField(
            model_name='product',
            name='productImg3',
            field=models.ImageField(blank=True, upload_to='productsImg'),
        ),
        migrations.AddField(
            model_name='product',
            name='productImg4',
            field=models.ImageField(blank=True, upload_to='productsImg'),
        ),
    ]
