# Generated by Django 3.0.7 on 2020-06-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0012_auto_20200620_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productImg4',
        ),
    ]
