# Generated by Django 3.0.7 on 2020-06-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0013_remove_product_productimg4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDescription',
            field=models.CharField(default='fhdj fd', max_length=500),
        ),
    ]
